program: train.py
name: Citation In-context Learning Hyper-parameter Tuning
method: bayes
metric:
  goal: maximize
  name: final/test_value
parameters:
  sft_epochs:
    min: 0.0001
    max: 0.1
    q: 5
  sft_lr:
    values: [1e-4, 1e-5, 1e-6, 1e-7, 1e-8]
  dataset:
    values: ['cora']
  group:
    values: ['sweep-citation-in-context']