base:
  pt_lr: 1e-7
  pt_epochs: 10
  pt_feat_p: 0.2
  pt_edge_p: 0.2
  pt_align_reg_lambda: 10
node:
  cora:
    normalize: "none"
    sft_lr: 1e-7
    sft_epochs: 100
    lr: 1e-4
    decay: 0
  citeseer:
    normalize: "batch"
    sft_lr: 1e-4
    sft_epochs: 100
    lr: 1e-4
    decay: 0
  pubmed:
    normalize: "none"
    sft_lr: 1e-6
    sft_epochs: 100
    lr: 1e-5
    decay: 1e-6
  dblp:
    normalize: "none"
    sft_lr: 1e-5
    sft_epochs: 100
    lr: 1e-4
    decay: 0
  arxiv23: