base:
  pt_lr: 1e-7
  pt_epochs: 10
  pt_feat_p: 0.2
  pt_edge_p: 0.2
  pt_align_reg_lambda: 10
node:
  cora:
    normalize: "none"
    sft_epochs: 50
    sft_lr: 1e-8
  citeseer:
    normalize: "none"
    sft_epochs: 50
    sft_lr: 1e-5
  pubmed:
    normalize: "none"
    sft_epochs: 20
    sft_lr: 1e-8
  arxiv23:
    normalize: "batch"
    sft_epochs: 5
    sft_lr: 1e-8
  dblp:
    normalize: "batch"
    sft_epochs: 120
    sft_lr: 1e-5
  bookhis:
    normalize: "none"
    sft_epochs: 20
    sft_lr: 1e-8
  bookchild:
    normalize: "batch"
    sft_epochs: 20
    sft_lr: 1e-8
  elecomp:
    normalize: "none"
    sft_epochs: 20
    sft_lr: 1e-8
  elephoto:
    normalize: "none"
    sft_epochs: 40
    sft_lr: 1e-8
  sportsfit:
    normalize: "none"
    sft_epochs: 10
    sft_lr: 1e-8
  amazonratings:
    normalize: "none"
    sft_epochs: 30
    sft_lr: 1e-5
edge:
  WN18RR:
    normalize: "batch"
    sft_epochs: 30
    sft_lr: 1e-4
  codex_s:
    normalize: "batch"
    sft_epochs: 10
    sft_lr: 1e-8
  codex_m:
    normalize: "batch"
    sft_epochs: 280
    sft_lr: 1e-8
  codex_l:
    normalize: "batch"
    sft_epochs: 230
    sft_lr: 1e-8
  NELL995:
    normalize: "batch"
    sft_epochs: 10
    sft_lr: 1e-8
  GDELT:
    normalize: "batch"
    sft_epochs: 170
    sft_lr: 1e-6
  ICEWS1819:
    normalize: "batch"
    sft_epochs: 100
    sft_lr: 1e-7
  Enron:
    normalize: "none"
    sft_epochs: 20
    sft_lr: 1e-4
  Googlemap_CT:
    normalize: "none"
    sft_epochs: 300
    sft_lr: 1e-6
graph:
  chemhiv:
    normalize: "none"
    sft_epochs: 5
    sft_lr: 1e-4
  bbbp:
    normalize: "batch"
    sft_epochs: 100
    sft_lr: 1e-6
  bace:
    normalize: "batch"
    sft_epochs: 20
    sft_lr: 1e-4
  toxcast:

  cyp450:
    normalize: "batch"
    sft_epochs: 90
    sft_lr: 1e-6
  tox21:
    normalize: "batch"
    sft_epochs: 15
    sft_lr: 1e-4
  muv:
    normalize: "batch"
    sft_epochs: 15
    sft_lr: 1e-8